### ISSUE TITLE
Dotted arrows not saved in json

### ISSUE THREAD

**Issue by cchanavat** [AT-290690/SoME2-Entry-CT#6]
the predefined trees don't save if the arrow is dotted or not 
nor the fact that the arrow is bent

**Comment by cchanavat** [comment]
if we only place point, and no arrow, it's not saved either
cf PREDIFINED_TREES[2] that has only two point placed

**Comment by AT-290690** [comment]
I have to revisit the save feature - will take a look.

**Comment by AT-290690** [comment]
I see - styles have to be re-applied

**Comment by AT-290690** [comment]
This should be resolved now!
